I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/fishing_bay.rpy", line 110, in script
    $ FRelationship+=1;
  File "game/fishing_bay.rpy", line 110, in <module>
    $ FRelationship+=1;
NameError: name 'FRelationship' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/fishing_bay.rpy", line 110, in script
    $ FRelationship+=1;
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/fishing_bay.rpy", line 110, in <module>
    $ FRelationship+=1;
NameError: name 'FRelationship' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
DingleProject 1.0
Thu Nov 21 14:13:56 2024
